object Versions {
    const val activityCompose = "1.3.1"
    const val accompanistSwipeRefresh = "0.19.0"
    const val appCompat = "1.3.1"
    const val compose = "1.0.3"
    const val constraintLayoutCompose = "1.0.0-rc01"
    const val coreKtx = "1.6.0"
    const val coroutines = "1.5.2"
    const val espresso = "3.4.0"
    const val gradleDependencies = "0.39.0"
    const val gradlePlugin = "7.0.2"
    const val hilt = "2.39.1"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val kotlin = "1.5.30"
    const val lifecycleKtx = "2.3.1"
    const val material = "1.4.0"
    const val okHttp = "4.9.2"
    const val retrofit = "2.9.0"
    const val viewModelCompose = "2.4.0-rc01"
}